# Generated by Django 3.1.4 on 2021-02-17 16:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_value', models.IntegerField(default=100, error_messages={'invalid': '“%(value)s” value must be an integer.', 'not_enough': 'you do not have enough cash_balance'}, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000000)])),
                ('notes', models.TextField(blank=True, default='', max_length=255)),
                ('trade_type', models.CharField(choices=[('BUY_COIN', 'Buy Coin'), ('BUY_CASH', 'Buy Cash'), ('SEND_COIN', 'Send Coin'), ('TRADE_COIN', 'Trade Coin')], default='SEND_COIN', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(blank=True, error_messages={'cant': 'You cant Send $$ for yourself', 'invalid': 'There is no such user'}, help_text='Entry wallet id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pmt_recipient', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pmt_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
